//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetails", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class FaultDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberUnfinancial", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MemberUnfinancial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountDueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BadgeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Rate_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Subs_Paid_TillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountDue {
            get {
                return this.AmountDueField;
            }
            set {
                if ((this.AmountDueField.Equals(value) != true)) {
                    this.AmountDueField = value;
                    this.RaisePropertyChanged("AmountDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BadgeNumber {
            get {
                return this.BadgeNumberField;
            }
            set {
                if ((this.BadgeNumberField.Equals(value) != true)) {
                    this.BadgeNumberField = value;
                    this.RaisePropertyChanged("BadgeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Rate_Number {
            get {
                return this.Rate_NumberField;
            }
            set {
                if ((this.Rate_NumberField.Equals(value) != true)) {
                    this.Rate_NumberField = value;
                    this.RaisePropertyChanged("Rate_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Subs_Paid_Till {
            get {
                return this.Subs_Paid_TillField;
            }
            set {
                if ((this.Subs_Paid_TillField.Equals(value) != true)) {
                    this.Subs_Paid_TillField = value;
                    this.RaisePropertyChanged("Subs_Paid_Till");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineStatus", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MachineStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEGMInUseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubID {
            get {
                return this.ClubIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubIDField, value) != true)) {
                    this.ClubIDField = value;
                    this.RaisePropertyChanged("ClubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEGMInUse {
            get {
                return this.IsEGMInUseField;
            }
            set {
                if ((this.IsEGMInUseField.Equals(value) != true)) {
                    this.IsEGMInUseField = value;
                    this.RaisePropertyChanged("IsEGMInUse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineDetails", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MachineDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denomination {
            get {
                return this.DenominationField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominationField, value) != true)) {
                    this.DenominationField = value;
                    this.RaisePropertyChanged("Denomination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((this.FloorField.Equals(value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacture {
            get {
                return this.ManufactureField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufactureField, value) != true)) {
                    this.ManufactureField = value;
                    this.RaisePropertyChanged("Manufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialField, value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineMeters", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MachineMeters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CancelCredit_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CancelCredit_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashIn_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashIn_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashOut_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashOut_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cashbox_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cashbox_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MeterUpdatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyIn_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyIn_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyOut_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyOut_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Stroke_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Stroke_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Turnover_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Turnover_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Wins_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Wins_OField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CancelCredit_C {
            get {
                return this.CancelCredit_CField;
            }
            set {
                if ((this.CancelCredit_CField.Equals(value) != true)) {
                    this.CancelCredit_CField = value;
                    this.RaisePropertyChanged("CancelCredit_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CancelCredit_O {
            get {
                return this.CancelCredit_OField;
            }
            set {
                if ((this.CancelCredit_OField.Equals(value) != true)) {
                    this.CancelCredit_OField = value;
                    this.RaisePropertyChanged("CancelCredit_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashIn_C {
            get {
                return this.CashIn_CField;
            }
            set {
                if ((this.CashIn_CField.Equals(value) != true)) {
                    this.CashIn_CField = value;
                    this.RaisePropertyChanged("CashIn_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashIn_O {
            get {
                return this.CashIn_OField;
            }
            set {
                if ((this.CashIn_OField.Equals(value) != true)) {
                    this.CashIn_OField = value;
                    this.RaisePropertyChanged("CashIn_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashOut_C {
            get {
                return this.CashOut_CField;
            }
            set {
                if ((this.CashOut_CField.Equals(value) != true)) {
                    this.CashOut_CField = value;
                    this.RaisePropertyChanged("CashOut_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashOut_O {
            get {
                return this.CashOut_OField;
            }
            set {
                if ((this.CashOut_OField.Equals(value) != true)) {
                    this.CashOut_OField = value;
                    this.RaisePropertyChanged("CashOut_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cashbox_C {
            get {
                return this.Cashbox_CField;
            }
            set {
                if ((this.Cashbox_CField.Equals(value) != true)) {
                    this.Cashbox_CField = value;
                    this.RaisePropertyChanged("Cashbox_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cashbox_O {
            get {
                return this.Cashbox_OField;
            }
            set {
                if ((this.Cashbox_OField.Equals(value) != true)) {
                    this.Cashbox_OField = value;
                    this.RaisePropertyChanged("Cashbox_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MeterUpdatedAt {
            get {
                return this.MeterUpdatedAtField;
            }
            set {
                if ((this.MeterUpdatedAtField.Equals(value) != true)) {
                    this.MeterUpdatedAtField = value;
                    this.RaisePropertyChanged("MeterUpdatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyIn_C {
            get {
                return this.MoneyIn_CField;
            }
            set {
                if ((this.MoneyIn_CField.Equals(value) != true)) {
                    this.MoneyIn_CField = value;
                    this.RaisePropertyChanged("MoneyIn_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyIn_O {
            get {
                return this.MoneyIn_OField;
            }
            set {
                if ((this.MoneyIn_OField.Equals(value) != true)) {
                    this.MoneyIn_OField = value;
                    this.RaisePropertyChanged("MoneyIn_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyOut_C {
            get {
                return this.MoneyOut_CField;
            }
            set {
                if ((this.MoneyOut_CField.Equals(value) != true)) {
                    this.MoneyOut_CField = value;
                    this.RaisePropertyChanged("MoneyOut_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyOut_O {
            get {
                return this.MoneyOut_OField;
            }
            set {
                if ((this.MoneyOut_OField.Equals(value) != true)) {
                    this.MoneyOut_OField = value;
                    this.RaisePropertyChanged("MoneyOut_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Stroke_C {
            get {
                return this.Stroke_CField;
            }
            set {
                if ((this.Stroke_CField.Equals(value) != true)) {
                    this.Stroke_CField = value;
                    this.RaisePropertyChanged("Stroke_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Stroke_O {
            get {
                return this.Stroke_OField;
            }
            set {
                if ((this.Stroke_OField.Equals(value) != true)) {
                    this.Stroke_OField = value;
                    this.RaisePropertyChanged("Stroke_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Turnover_C {
            get {
                return this.Turnover_CField;
            }
            set {
                if ((this.Turnover_CField.Equals(value) != true)) {
                    this.Turnover_CField = value;
                    this.RaisePropertyChanged("Turnover_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Turnover_O {
            get {
                return this.Turnover_OField;
            }
            set {
                if ((this.Turnover_OField.Equals(value) != true)) {
                    this.Turnover_OField = value;
                    this.RaisePropertyChanged("Turnover_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Wins_C {
            get {
                return this.Wins_CField;
            }
            set {
                if ((this.Wins_CField.Equals(value) != true)) {
                    this.Wins_CField = value;
                    this.RaisePropertyChanged("Wins_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Wins_O {
            get {
                return this.Wins_OField;
            }
            set {
                if ((this.Wins_OField.Equals(value) != true)) {
                    this.Wins_OField = value;
                    this.RaisePropertyChanged("Wins_O");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSPointsResult", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class POSPointsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewPtsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewPtsBalance {
            get {
                return this.NewPtsBalanceField;
            }
            set {
                if ((this.NewPtsBalanceField.Equals(value) != true)) {
                    this.NewPtsBalanceField = value;
                    this.RaisePropertyChanged("NewPtsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ebetgroup.com.au/EPSGatewayService", ConfigurationName="ServiceReference1.IGateWayService")]
    public interface IGateWayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberDetails", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberDetailsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberDetailsFaultDe" +
            "tailsFault", Name="FaultDetails")]
        string GetMemberDetails(int badgeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetUnfinancial", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetUnfinancialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetUnfinancialFaultDeta" +
            "ilsFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.MemberUnfinancial[] GetUnfinancial(System.DateTime subsPaidTill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/InternetReceipt", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/InternetReceiptResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/InternetReceiptFaultDet" +
            "ailsFault", Name="FaultDetails")]
        int InternetReceipt(int badgeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberActivity_FullC" +
            "ardData", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberActivity_FullC" +
            "ardDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberActivity_FullC" +
            "ardDataFaultDetailsFault", Name="FaultDetails")]
        string GetMemberActivity_FullCardData(string code, string cardData, System.DateTime entryTime, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetTotalMachinesInPlay", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetTotalMachinesInPlayR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetTotalMachinesInPlayF" +
            "aultDetailsFault", Name="FaultDetails")]
        string GetTotalMachinesInPlay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineStatus", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineStatusRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineStatusFaultDe" +
            "tailsFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.MachineStatus[] GetMachineStatus(string clubID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineDetails", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineDetailsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineDetailsFaultD" +
            "etailsFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.MachineDetails[] GetMachineDetails(string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineMeters", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineMetersRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineMetersFaultDe" +
            "tailsFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.MachineMeters[] GetMachineMeters(int mID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/AddPOSPoints", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/AddPOSPointsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/AddPOSPointsFaultDetail" +
            "sFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.POSPointsResult AddPOSPoints(int badgeNumber, int bptsAdjust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RedeemPOSPoints", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RedeemPOSPointsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RedeemPOSPointsFaultDet" +
            "ailsFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.POSPointsResult RedeemPOSPoints(int badgeNumber, int bptsAdjust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RefundPOSPoints", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RefundPOSPointsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RefundPOSPointsFaultDet" +
            "ailsFault", Name="FaultDetails")]
        WpfApplication1.ServiceReference1.POSPointsResult RefundPOSPoints(int badgeNumber, int bptsAdjust);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGateWayServiceChannel : WpfApplication1.ServiceReference1.IGateWayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GateWayServiceClient : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference1.IGateWayService>, WpfApplication1.ServiceReference1.IGateWayService {
        
        public GateWayServiceClient() {
        }
        
        public GateWayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateWayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMemberDetails(int badgeNumber) {
            return base.Channel.GetMemberDetails(badgeNumber);
        }
        
        public WpfApplication1.ServiceReference1.MemberUnfinancial[] GetUnfinancial(System.DateTime subsPaidTill) {
            return base.Channel.GetUnfinancial(subsPaidTill);
        }
        
        public int InternetReceipt(int badgeNumber) {
            return base.Channel.InternetReceipt(badgeNumber);
        }
        
        public string GetMemberActivity_FullCardData(string code, string cardData, System.DateTime entryTime, string group) {
            return base.Channel.GetMemberActivity_FullCardData(code, cardData, entryTime, group);
        }
        
        public string GetTotalMachinesInPlay() {
            return base.Channel.GetTotalMachinesInPlay();
        }
        
        public WpfApplication1.ServiceReference1.MachineStatus[] GetMachineStatus(string clubID) {
            return base.Channel.GetMachineStatus(clubID);
        }
        
        public WpfApplication1.ServiceReference1.MachineDetails[] GetMachineDetails(string serial) {
            return base.Channel.GetMachineDetails(serial);
        }
        
        public WpfApplication1.ServiceReference1.MachineMeters[] GetMachineMeters(int mID) {
            return base.Channel.GetMachineMeters(mID);
        }
        
        public WpfApplication1.ServiceReference1.POSPointsResult AddPOSPoints(int badgeNumber, int bptsAdjust) {
            return base.Channel.AddPOSPoints(badgeNumber, bptsAdjust);
        }
        
        public WpfApplication1.ServiceReference1.POSPointsResult RedeemPOSPoints(int badgeNumber, int bptsAdjust) {
            return base.Channel.RedeemPOSPoints(badgeNumber, bptsAdjust);
        }
        
        public WpfApplication1.ServiceReference1.POSPointsResult RefundPOSPoints(int badgeNumber, int bptsAdjust) {
            return base.Channel.RefundPOSPoints(badgeNumber, bptsAdjust);
        }
    }
}
