SETLOCAL
SET TARGETPATH=\private\dev\project\VS\Binary\Develop\
SET PROJECTDIR=%1
SET OUTDIR=%2
SET TARGETFILENAME=%3
SET TARGETNAME=%4

IF [%5] NEQ [] (SET TARGETFOLDER=%5) ELSE (SET TARGETFOLDER=.)

echo Copying output file to %TARGETPATH%%TARGETFOLDER%
xcopy /y "%PROJECTDIR%%OUTDIR%%TARGETFILENAME%" "%TARGETPATH%%TARGETFOLDER%\"

if exist "%PROJECTDIR%%OUTDIR%%TARGETFILENAME%.config" (
  echo Copying config file
  xcopy /y "%PROJECTDIR%%OUTDIR%%TARGETFILENAME%.config" "%TARGETPATH%%TARGETFOLDER%\"
)

if exist "%PROJECTDIR%%OUTDIR%%TARGETNAME%.pdb" (
  echo Copying debug file
  xcopy /y "%PROJECTDIR%%OUTDIR%%TARGETNAME%.pdb" "%TARGETPATH%%TARGETFOLDER%\"
)

ENDLOCAL