//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetails", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class FaultDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberUnfinancial", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MemberUnfinancial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountDueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BadgeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Rate_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Subs_Paid_TillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountDue {
            get {
                return this.AmountDueField;
            }
            set {
                if ((this.AmountDueField.Equals(value) != true)) {
                    this.AmountDueField = value;
                    this.RaisePropertyChanged("AmountDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BadgeNumber {
            get {
                return this.BadgeNumberField;
            }
            set {
                if ((this.BadgeNumberField.Equals(value) != true)) {
                    this.BadgeNumberField = value;
                    this.RaisePropertyChanged("BadgeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Rate_Number {
            get {
                return this.Rate_NumberField;
            }
            set {
                if ((this.Rate_NumberField.Equals(value) != true)) {
                    this.Rate_NumberField = value;
                    this.RaisePropertyChanged("Rate_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Subs_Paid_Till {
            get {
                return this.Subs_Paid_TillField;
            }
            set {
                if ((this.Subs_Paid_TillField.Equals(value) != true)) {
                    this.Subs_Paid_TillField = value;
                    this.RaisePropertyChanged("Subs_Paid_Till");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineStatus", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MachineStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CardInAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EpsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEGMInUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CardInAt {
            get {
                return this.CardInAtField;
            }
            set {
                if ((this.CardInAtField.Equals(value) != true)) {
                    this.CardInAtField = value;
                    this.RaisePropertyChanged("CardInAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubID {
            get {
                return this.ClubIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubIDField, value) != true)) {
                    this.ClubIDField = value;
                    this.RaisePropertyChanged("ClubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EpsID {
            get {
                return this.EpsIDField;
            }
            set {
                if ((this.EpsIDField.Equals(value) != true)) {
                    this.EpsIDField = value;
                    this.RaisePropertyChanged("EpsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEGMInUse {
            get {
                return this.IsEGMInUseField;
            }
            set {
                if ((this.IsEGMInUseField.Equals(value) != true)) {
                    this.IsEGMInUseField = value;
                    this.RaisePropertyChanged("IsEGMInUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((this.SessionIDField.Equals(value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Turnover {
            get {
                return this.TurnoverField;
            }
            set {
                if ((this.TurnoverField.Equals(value) != true)) {
                    this.TurnoverField = value;
                    this.RaisePropertyChanged("Turnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineDetails", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MachineDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubID {
            get {
                return this.ClubIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubIDField, value) != true)) {
                    this.ClubIDField = value;
                    this.RaisePropertyChanged("ClubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denomination {
            get {
                return this.DenominationField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominationField, value) != true)) {
                    this.DenominationField = value;
                    this.RaisePropertyChanged("Denomination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((this.FloorField.Equals(value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacture {
            get {
                return this.ManufactureField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufactureField, value) != true)) {
                    this.ManufactureField = value;
                    this.RaisePropertyChanged("Manufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialField, value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineMeters", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class MachineMeters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CancelCredit_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CancelCredit_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashIn_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashIn_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashOut_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CashOut_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cashbox_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Cashbox_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MeterUpdatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyIn_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyIn_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyOut_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyOut_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Stroke_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Stroke_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Turnover_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Turnover_OField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Wins_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Wins_OField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CancelCredit_C {
            get {
                return this.CancelCredit_CField;
            }
            set {
                if ((this.CancelCredit_CField.Equals(value) != true)) {
                    this.CancelCredit_CField = value;
                    this.RaisePropertyChanged("CancelCredit_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CancelCredit_O {
            get {
                return this.CancelCredit_OField;
            }
            set {
                if ((this.CancelCredit_OField.Equals(value) != true)) {
                    this.CancelCredit_OField = value;
                    this.RaisePropertyChanged("CancelCredit_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashIn_C {
            get {
                return this.CashIn_CField;
            }
            set {
                if ((this.CashIn_CField.Equals(value) != true)) {
                    this.CashIn_CField = value;
                    this.RaisePropertyChanged("CashIn_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashIn_O {
            get {
                return this.CashIn_OField;
            }
            set {
                if ((this.CashIn_OField.Equals(value) != true)) {
                    this.CashIn_OField = value;
                    this.RaisePropertyChanged("CashIn_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashOut_C {
            get {
                return this.CashOut_CField;
            }
            set {
                if ((this.CashOut_CField.Equals(value) != true)) {
                    this.CashOut_CField = value;
                    this.RaisePropertyChanged("CashOut_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CashOut_O {
            get {
                return this.CashOut_OField;
            }
            set {
                if ((this.CashOut_OField.Equals(value) != true)) {
                    this.CashOut_OField = value;
                    this.RaisePropertyChanged("CashOut_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cashbox_C {
            get {
                return this.Cashbox_CField;
            }
            set {
                if ((this.Cashbox_CField.Equals(value) != true)) {
                    this.Cashbox_CField = value;
                    this.RaisePropertyChanged("Cashbox_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cashbox_O {
            get {
                return this.Cashbox_OField;
            }
            set {
                if ((this.Cashbox_OField.Equals(value) != true)) {
                    this.Cashbox_OField = value;
                    this.RaisePropertyChanged("Cashbox_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MID {
            get {
                return this.MIDField;
            }
            set {
                if ((this.MIDField.Equals(value) != true)) {
                    this.MIDField = value;
                    this.RaisePropertyChanged("MID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MeterUpdatedAt {
            get {
                return this.MeterUpdatedAtField;
            }
            set {
                if ((this.MeterUpdatedAtField.Equals(value) != true)) {
                    this.MeterUpdatedAtField = value;
                    this.RaisePropertyChanged("MeterUpdatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyIn_C {
            get {
                return this.MoneyIn_CField;
            }
            set {
                if ((this.MoneyIn_CField.Equals(value) != true)) {
                    this.MoneyIn_CField = value;
                    this.RaisePropertyChanged("MoneyIn_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyIn_O {
            get {
                return this.MoneyIn_OField;
            }
            set {
                if ((this.MoneyIn_OField.Equals(value) != true)) {
                    this.MoneyIn_OField = value;
                    this.RaisePropertyChanged("MoneyIn_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyOut_C {
            get {
                return this.MoneyOut_CField;
            }
            set {
                if ((this.MoneyOut_CField.Equals(value) != true)) {
                    this.MoneyOut_CField = value;
                    this.RaisePropertyChanged("MoneyOut_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyOut_O {
            get {
                return this.MoneyOut_OField;
            }
            set {
                if ((this.MoneyOut_OField.Equals(value) != true)) {
                    this.MoneyOut_OField = value;
                    this.RaisePropertyChanged("MoneyOut_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Stroke_C {
            get {
                return this.Stroke_CField;
            }
            set {
                if ((this.Stroke_CField.Equals(value) != true)) {
                    this.Stroke_CField = value;
                    this.RaisePropertyChanged("Stroke_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Stroke_O {
            get {
                return this.Stroke_OField;
            }
            set {
                if ((this.Stroke_OField.Equals(value) != true)) {
                    this.Stroke_OField = value;
                    this.RaisePropertyChanged("Stroke_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Turnover_C {
            get {
                return this.Turnover_CField;
            }
            set {
                if ((this.Turnover_CField.Equals(value) != true)) {
                    this.Turnover_CField = value;
                    this.RaisePropertyChanged("Turnover_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Turnover_O {
            get {
                return this.Turnover_OField;
            }
            set {
                if ((this.Turnover_OField.Equals(value) != true)) {
                    this.Turnover_OField = value;
                    this.RaisePropertyChanged("Turnover_O");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Wins_C {
            get {
                return this.Wins_CField;
            }
            set {
                if ((this.Wins_CField.Equals(value) != true)) {
                    this.Wins_CField = value;
                    this.RaisePropertyChanged("Wins_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Wins_O {
            get {
                return this.Wins_OField;
            }
            set {
                if ((this.Wins_OField.Equals(value) != true)) {
                    this.Wins_OField = value;
                    this.RaisePropertyChanged("Wins_O");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSPointsResult", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class POSPointsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewPtsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewPtsBalance {
            get {
                return this.NewPtsBalanceField;
            }
            set {
                if ((this.NewPtsBalanceField.Equals(value) != true)) {
                    this.NewPtsBalanceField = value;
                    this.RaisePropertyChanged("NewPtsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetersReply", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common.QGCEGatewayMessages")]
    [System.SerializableAttribute()]
    public partial class MetersReply : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.MeterSnapshot[] MeterCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.QueryResult OperationalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.MeterSnapshot[] MeterCollection {
            get {
                return this.MeterCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterCollectionField, value) != true)) {
                    this.MeterCollectionField = value;
                    this.RaisePropertyChanged("MeterCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.QueryResult OperationalResult {
            get {
                return this.OperationalResultField;
            }
            set {
                if ((this.OperationalResultField.Equals(value) != true)) {
                    this.OperationalResultField = value;
                    this.RaisePropertyChanged("OperationalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterSnapshot", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common.QGCEGatewayMessages")]
    [System.SerializableAttribute()]
    public partial class MeterSnapshot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.MeterDetail[] CurrentMetersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.EgmModes EgmModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.EgmStatuses EgmStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MachineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.EgmMeterType MeterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint PlayerTurnoverInSessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SnapshotTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.MeterDetail[] CurrentMeters {
            get {
                return this.CurrentMetersField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentMetersField, value) != true)) {
                    this.CurrentMetersField = value;
                    this.RaisePropertyChanged("CurrentMeters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.EgmModes EgmMode {
            get {
                return this.EgmModeField;
            }
            set {
                if ((this.EgmModeField.Equals(value) != true)) {
                    this.EgmModeField = value;
                    this.RaisePropertyChanged("EgmMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.EgmStatuses EgmState {
            get {
                return this.EgmStateField;
            }
            set {
                if ((this.EgmStateField.Equals(value) != true)) {
                    this.EgmStateField = value;
                    this.RaisePropertyChanged("EgmState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MachineID {
            get {
                return this.MachineIDField;
            }
            set {
                if ((this.MachineIDField.Equals(value) != true)) {
                    this.MachineIDField = value;
                    this.RaisePropertyChanged("MachineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((this.MemberIDField.Equals(value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.EgmMeterType MeterType {
            get {
                return this.MeterTypeField;
            }
            set {
                if ((this.MeterTypeField.Equals(value) != true)) {
                    this.MeterTypeField = value;
                    this.RaisePropertyChanged("MeterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint PlayerTurnoverInSession {
            get {
                return this.PlayerTurnoverInSessionField;
            }
            set {
                if ((this.PlayerTurnoverInSessionField.Equals(value) != true)) {
                    this.PlayerTurnoverInSessionField = value;
                    this.RaisePropertyChanged("PlayerTurnoverInSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SnapshotTime {
            get {
                return this.SnapshotTimeField;
            }
            set {
                if ((this.SnapshotTimeField.Equals(value) != true)) {
                    this.SnapshotTimeField = value;
                    this.RaisePropertyChanged("SnapshotTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common.QGCEGatewayMessages")]
    public enum QueryResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        noMachines = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        egmNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        serverBusy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        otherError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterDetail", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common.QGCEGatewayMessages")]
    [System.SerializableAttribute()]
    public partial class MeterDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.EgmMeterId IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint PreviousValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.EgmMeterId ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChangedTime {
            get {
                return this.LastChangedTimeField;
            }
            set {
                if ((this.LastChangedTimeField.Equals(value) != true)) {
                    this.LastChangedTimeField = value;
                    this.RaisePropertyChanged("LastChangedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint PreviousValue {
            get {
                return this.PreviousValueField;
            }
            set {
                if ((this.PreviousValueField.Equals(value) != true)) {
                    this.PreviousValueField = value;
                    this.RaisePropertyChanged("PreviousValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgmModes", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common")]
    public enum EgmModes : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Test = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attendant = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Idle = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Play = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reserve = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestScreen = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitBet = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payout = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 100,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgmStatuses", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common")]
    public enum EgmStatuses : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Event = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regatt = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GmComm = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Test = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableBySWJP = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableBySWJPNoBroadcast = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableTournament = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableByECTFailed = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableByTicketOutRequest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisableByTicketOutPrinting = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 100,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgmMeterType", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common")]
    public enum EgmMeterType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartDay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RamReset = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndOfDay = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decommission = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commissioned = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hourly = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemStartDay = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Snapshot = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decommission2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RamClearAdjust = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartDay2 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndDay2 = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCRamClear = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardInSnapsoh = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardOutSnapshot = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCInSnapshot = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCOutSnapshot = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 250,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgmMeterId", Namespace="http://schemas.datacontract.org/2004/07/Ebet.Common")]
    public enum EgmMeterId : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        gameWins = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        stroke = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        turnover = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        wins = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        csi = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cso = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        coi = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        coo = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        hopper = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cashBox = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        refill = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cancel = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        totalWins = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        credits = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        jpCont = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        jpWon = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cto = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        tci = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        tco = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sapWins = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lpWins = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ni = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nic = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        d5In = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        d10In = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        d20In = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        d50In = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        d100In = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rcrt = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rcrw = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        undefined1 = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        undefined2 = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LPE = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CIE = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRE = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cti = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pidacc = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        tgWins = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        tsapWins = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rejNots = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        gTurnover = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        gWins = 41,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionDetails", Namespace="http://ebetgroup.com.au/EPSGatewayService")]
    [System.SerializableAttribute()]
    public partial class SessionDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CardInAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CardOutAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClosingBptsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingStrokeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingTurnOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurStrokeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurTurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EGMSessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EPSIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCashlessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MachIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpeningBPtsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningStrokeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningTurnOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PreStrokeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PreTurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PreWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SessionStrokeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SessionTurnOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SessionWinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CardInAt {
            get {
                return this.CardInAtField;
            }
            set {
                if ((this.CardInAtField.Equals(value) != true)) {
                    this.CardInAtField = value;
                    this.RaisePropertyChanged("CardInAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CardOutAt {
            get {
                return this.CardOutAtField;
            }
            set {
                if ((this.CardOutAtField.Equals(value) != true)) {
                    this.CardOutAtField = value;
                    this.RaisePropertyChanged("CardOutAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClosingBptsBalance {
            get {
                return this.ClosingBptsBalanceField;
            }
            set {
                if ((this.ClosingBptsBalanceField.Equals(value) != true)) {
                    this.ClosingBptsBalanceField = value;
                    this.RaisePropertyChanged("ClosingBptsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosingStroke {
            get {
                return this.ClosingStrokeField;
            }
            set {
                if ((this.ClosingStrokeField.Equals(value) != true)) {
                    this.ClosingStrokeField = value;
                    this.RaisePropertyChanged("ClosingStroke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosingTurnOver {
            get {
                return this.ClosingTurnOverField;
            }
            set {
                if ((this.ClosingTurnOverField.Equals(value) != true)) {
                    this.ClosingTurnOverField = value;
                    this.RaisePropertyChanged("ClosingTurnOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosingWins {
            get {
                return this.ClosingWinsField;
            }
            set {
                if ((this.ClosingWinsField.Equals(value) != true)) {
                    this.ClosingWinsField = value;
                    this.RaisePropertyChanged("ClosingWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurStroke {
            get {
                return this.CurStrokeField;
            }
            set {
                if ((this.CurStrokeField.Equals(value) != true)) {
                    this.CurStrokeField = value;
                    this.RaisePropertyChanged("CurStroke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurTurnover {
            get {
                return this.CurTurnoverField;
            }
            set {
                if ((this.CurTurnoverField.Equals(value) != true)) {
                    this.CurTurnoverField = value;
                    this.RaisePropertyChanged("CurTurnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurWins {
            get {
                return this.CurWinsField;
            }
            set {
                if ((this.CurWinsField.Equals(value) != true)) {
                    this.CurWinsField = value;
                    this.RaisePropertyChanged("CurWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EGMSessionID {
            get {
                return this.EGMSessionIDField;
            }
            set {
                if ((this.EGMSessionIDField.Equals(value) != true)) {
                    this.EGMSessionIDField = value;
                    this.RaisePropertyChanged("EGMSessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EPSID {
            get {
                return this.EPSIDField;
            }
            set {
                if ((this.EPSIDField.Equals(value) != true)) {
                    this.EPSIDField = value;
                    this.RaisePropertyChanged("EPSID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCashless {
            get {
                return this.IsCashlessField;
            }
            set {
                if ((this.IsCashlessField.Equals(value) != true)) {
                    this.IsCashlessField = value;
                    this.RaisePropertyChanged("IsCashless");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MachID {
            get {
                return this.MachIDField;
            }
            set {
                if ((this.MachIDField.Equals(value) != true)) {
                    this.MachIDField = value;
                    this.RaisePropertyChanged("MachID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpeningBPtsBalance {
            get {
                return this.OpeningBPtsBalanceField;
            }
            set {
                if ((this.OpeningBPtsBalanceField.Equals(value) != true)) {
                    this.OpeningBPtsBalanceField = value;
                    this.RaisePropertyChanged("OpeningBPtsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OpeningStroke {
            get {
                return this.OpeningStrokeField;
            }
            set {
                if ((this.OpeningStrokeField.Equals(value) != true)) {
                    this.OpeningStrokeField = value;
                    this.RaisePropertyChanged("OpeningStroke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OpeningTurnOver {
            get {
                return this.OpeningTurnOverField;
            }
            set {
                if ((this.OpeningTurnOverField.Equals(value) != true)) {
                    this.OpeningTurnOverField = value;
                    this.RaisePropertyChanged("OpeningTurnOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OpeningWins {
            get {
                return this.OpeningWinsField;
            }
            set {
                if ((this.OpeningWinsField.Equals(value) != true)) {
                    this.OpeningWinsField = value;
                    this.RaisePropertyChanged("OpeningWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreStroke {
            get {
                return this.PreStrokeField;
            }
            set {
                if ((this.PreStrokeField.Equals(value) != true)) {
                    this.PreStrokeField = value;
                    this.RaisePropertyChanged("PreStroke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreTurnover {
            get {
                return this.PreTurnoverField;
            }
            set {
                if ((this.PreTurnoverField.Equals(value) != true)) {
                    this.PreTurnoverField = value;
                    this.RaisePropertyChanged("PreTurnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreWins {
            get {
                return this.PreWinsField;
            }
            set {
                if ((this.PreWinsField.Equals(value) != true)) {
                    this.PreWinsField = value;
                    this.RaisePropertyChanged("PreWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SessionStroke {
            get {
                return this.SessionStrokeField;
            }
            set {
                if ((this.SessionStrokeField.Equals(value) != true)) {
                    this.SessionStrokeField = value;
                    this.RaisePropertyChanged("SessionStroke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SessionTurnOver {
            get {
                return this.SessionTurnOverField;
            }
            set {
                if ((this.SessionTurnOverField.Equals(value) != true)) {
                    this.SessionTurnOverField = value;
                    this.RaisePropertyChanged("SessionTurnOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SessionWins {
            get {
                return this.SessionWinsField;
            }
            set {
                if ((this.SessionWinsField.Equals(value) != true)) {
                    this.SessionWinsField = value;
                    this.RaisePropertyChanged("SessionWins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common.GatewayMetersReply", Namespace="http://schemas.datacontract.org/2004/07/EPSGateway.Business")]
    [System.SerializableAttribute()]
    public partial class CommonGatewayMetersReply : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.CommonGatewayMeterSnapshot[] MeterCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.CommonGatewayQueryResult OperationalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.CommonGatewayMeterSnapshot[] MeterCollection {
            get {
                return this.MeterCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterCollectionField, value) != true)) {
                    this.MeterCollectionField = value;
                    this.RaisePropertyChanged("MeterCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.CommonGatewayQueryResult OperationalResult {
            get {
                return this.OperationalResultField;
            }
            set {
                if ((this.OperationalResultField.Equals(value) != true)) {
                    this.OperationalResultField = value;
                    this.RaisePropertyChanged("OperationalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common.GatewayMeterSnapshot", Namespace="http://schemas.datacontract.org/2004/07/EPSGateway.Business")]
    [System.SerializableAttribute()]
    public partial class CommonGatewayMeterSnapshot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.CommonGatewayMeterDetail[] CurrentMetersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication2.ServiceReference1.CommonGatewayEgmModes EgmModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EgmStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MachineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint PlayerTurnoverInSessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SnapshotTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.CommonGatewayMeterDetail[] CurrentMeters {
            get {
                return this.CurrentMetersField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentMetersField, value) != true)) {
                    this.CurrentMetersField = value;
                    this.RaisePropertyChanged("CurrentMeters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication2.ServiceReference1.CommonGatewayEgmModes EgmMode {
            get {
                return this.EgmModeField;
            }
            set {
                if ((this.EgmModeField.Equals(value) != true)) {
                    this.EgmModeField = value;
                    this.RaisePropertyChanged("EgmMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EgmState {
            get {
                return this.EgmStateField;
            }
            set {
                if ((object.ReferenceEquals(this.EgmStateField, value) != true)) {
                    this.EgmStateField = value;
                    this.RaisePropertyChanged("EgmState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MachineID {
            get {
                return this.MachineIDField;
            }
            set {
                if ((this.MachineIDField.Equals(value) != true)) {
                    this.MachineIDField = value;
                    this.RaisePropertyChanged("MachineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((this.MemberIDField.Equals(value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberName {
            get {
                return this.MemberNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberNameField, value) != true)) {
                    this.MemberNameField = value;
                    this.RaisePropertyChanged("MemberName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint PlayerTurnoverInSession {
            get {
                return this.PlayerTurnoverInSessionField;
            }
            set {
                if ((this.PlayerTurnoverInSessionField.Equals(value) != true)) {
                    this.PlayerTurnoverInSessionField = value;
                    this.RaisePropertyChanged("PlayerTurnoverInSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SnapshotTime {
            get {
                return this.SnapshotTimeField;
            }
            set {
                if ((this.SnapshotTimeField.Equals(value) != true)) {
                    this.SnapshotTimeField = value;
                    this.RaisePropertyChanged("SnapshotTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common.GatewayQueryResult", Namespace="http://schemas.datacontract.org/2004/07/EPSGateway.Business")]
    public enum CommonGatewayQueryResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        noMachines = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        egmNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        serverBusy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        otherError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common.GatewayMeterDetail", Namespace="http://schemas.datacontract.org/2004/07/EPSGateway.Business")]
    [System.SerializableAttribute()]
    public partial class CommonGatewayMeterDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MeterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PreviousValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChangedTime {
            get {
                return this.LastChangedTimeField;
            }
            set {
                if ((this.LastChangedTimeField.Equals(value) != true)) {
                    this.LastChangedTimeField = value;
                    this.RaisePropertyChanged("LastChangedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MeterID {
            get {
                return this.MeterIDField;
            }
            set {
                if ((this.MeterIDField.Equals(value) != true)) {
                    this.MeterIDField = value;
                    this.RaisePropertyChanged("MeterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterName {
            get {
                return this.MeterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNameField, value) != true)) {
                    this.MeterNameField = value;
                    this.RaisePropertyChanged("MeterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PreviousValue {
            get {
                return this.PreviousValueField;
            }
            set {
                if ((this.PreviousValueField.Equals(value) != true)) {
                    this.PreviousValueField = value;
                    this.RaisePropertyChanged("PreviousValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Common.GatewayEgmModes", Namespace="http://schemas.datacontract.org/2004/07/EPSGateway.Business")]
    public enum CommonGatewayEgmModes : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Test = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attendant = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Idle = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Play = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reserve = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestScreen = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitBet = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payout = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 100,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ebetgroup.com.au/EPSGatewayService", ConfigurationName="ServiceReference1.IGateWayService")]
    public interface IGateWayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberDetails", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberDetailsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberDetailsFaultDe" +
            "tailsFault", Name="FaultDetails")]
        string GetMemberDetails(int badgeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMember", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberFaultDetailsFa" +
            "ult", Name="FaultDetails")]
        string GetMember(int badgeNumber, string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetUnfinancial", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetUnfinancialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetUnfinancialFaultDeta" +
            "ilsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.MemberUnfinancial[] GetUnfinancial(System.DateTime subsPaidTill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/InternetReceipt", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/InternetReceiptResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/InternetReceiptFaultDet" +
            "ailsFault", Name="FaultDetails")]
        int InternetReceipt(int badgeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberActivity_FullC" +
            "ardData", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberActivity_FullC" +
            "ardDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMemberActivity_FullC" +
            "ardDataFaultDetailsFault", Name="FaultDetails")]
        string GetMemberActivity_FullCardData(string code, string cardData, System.DateTime entryTime, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetTotalMachinesInPlay", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetTotalMachinesInPlayR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetTotalMachinesInPlayF" +
            "aultDetailsFault", Name="FaultDetails")]
        string GetTotalMachinesInPlay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineStatus", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineStatusRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineStatusFaultDe" +
            "tailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.MachineStatus[] GetMachineStatus(string clubID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineDetails", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineDetailsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineDetailsFaultD" +
            "etailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.MachineDetails[] GetMachineDetails(int mID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineMeters", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineMetersRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineMetersFaultDe" +
            "tailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.MachineMeters[] GetMachineMeters(int mID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/AddPOSPoints", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/AddPOSPointsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/AddPOSPointsFaultDetail" +
            "sFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.POSPointsResult AddPOSPoints(int badgeNumber, int bptsAdjust, int deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RedeemPOSPoints", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RedeemPOSPointsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RedeemPOSPointsFaultDet" +
            "ailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.POSPointsResult RedeemPOSPoints(int badgeNumber, int bptsAdjust, int deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RefundPOSPoints", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RefundPOSPointsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/RefundPOSPointsFaultDet" +
            "ailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.POSPointsResult RefundPOSPoints(int badgeNumber, int bptsAdjust, int deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineCurrentMeters" +
            "", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineCurrentMeters" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineCurrentMeters" +
            "FaultDetailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.MetersReply GetMachineCurrentMeters(int mID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetSessionDetails", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetSessionDetailsRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetSessionDetailsFaultD" +
            "etailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.SessionDetails GetSessionDetails(int sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineCurrentMeters" +
            "ByDate", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineCurrentMeters" +
            "ByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineCurrentMeters" +
            "ByDateFaultDetailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.MetersReply GetMachineCurrentMetersByDate(int mID, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineRealMeters", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineRealMetersRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineRealMetersFau" +
            "ltDetailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.CommonGatewayMetersReply GetMachineRealMeters(int mID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineRealMetersByD" +
            "ate", ReplyAction="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineRealMetersByD" +
            "ateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication2.ServiceReference1.FaultDetails), Action="http://ebetgroup.com.au/EPSGatewayService/IGateWayService/GetMachineRealMetersByD" +
            "ateFaultDetailsFault", Name="FaultDetails")]
        ConsoleApplication2.ServiceReference1.CommonGatewayMetersReply GetMachineRealMetersByDate(int mID, System.DateTime dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGateWayServiceChannel : ConsoleApplication2.ServiceReference1.IGateWayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GateWayServiceClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference1.IGateWayService>, ConsoleApplication2.ServiceReference1.IGateWayService {
        
        public GateWayServiceClient() {
        }
        
        public GateWayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateWayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMemberDetails(int badgeNumber) {
            return base.Channel.GetMemberDetails(badgeNumber);
        }
        
        public string GetMember(int badgeNumber, string cardNumber) {
            return base.Channel.GetMember(badgeNumber, cardNumber);
        }
        
        public ConsoleApplication2.ServiceReference1.MemberUnfinancial[] GetUnfinancial(System.DateTime subsPaidTill) {
            return base.Channel.GetUnfinancial(subsPaidTill);
        }
        
        public int InternetReceipt(int badgeNumber) {
            return base.Channel.InternetReceipt(badgeNumber);
        }
        
        public string GetMemberActivity_FullCardData(string code, string cardData, System.DateTime entryTime, string group) {
            return base.Channel.GetMemberActivity_FullCardData(code, cardData, entryTime, group);
        }
        
        public string GetTotalMachinesInPlay() {
            return base.Channel.GetTotalMachinesInPlay();
        }
        
        public ConsoleApplication2.ServiceReference1.MachineStatus[] GetMachineStatus(string clubID) {
            return base.Channel.GetMachineStatus(clubID);
        }
        
        public ConsoleApplication2.ServiceReference1.MachineDetails[] GetMachineDetails(int mID) {
            return base.Channel.GetMachineDetails(mID);
        }
        
        public ConsoleApplication2.ServiceReference1.MachineMeters[] GetMachineMeters(int mID) {
            return base.Channel.GetMachineMeters(mID);
        }
        
        public ConsoleApplication2.ServiceReference1.POSPointsResult AddPOSPoints(int badgeNumber, int bptsAdjust, int deviceID) {
            return base.Channel.AddPOSPoints(badgeNumber, bptsAdjust, deviceID);
        }
        
        public ConsoleApplication2.ServiceReference1.POSPointsResult RedeemPOSPoints(int badgeNumber, int bptsAdjust, int deviceID) {
            return base.Channel.RedeemPOSPoints(badgeNumber, bptsAdjust, deviceID);
        }
        
        public ConsoleApplication2.ServiceReference1.POSPointsResult RefundPOSPoints(int badgeNumber, int bptsAdjust, int deviceID) {
            return base.Channel.RefundPOSPoints(badgeNumber, bptsAdjust, deviceID);
        }
        
        public ConsoleApplication2.ServiceReference1.MetersReply GetMachineCurrentMeters(int mID) {
            return base.Channel.GetMachineCurrentMeters(mID);
        }
        
        public ConsoleApplication2.ServiceReference1.SessionDetails GetSessionDetails(int sessionID) {
            return base.Channel.GetSessionDetails(sessionID);
        }
        
        public ConsoleApplication2.ServiceReference1.MetersReply GetMachineCurrentMetersByDate(int mID, System.DateTime dt) {
            return base.Channel.GetMachineCurrentMetersByDate(mID, dt);
        }
        
        public ConsoleApplication2.ServiceReference1.CommonGatewayMetersReply GetMachineRealMeters(int mID) {
            return base.Channel.GetMachineRealMeters(mID);
        }
        
        public ConsoleApplication2.ServiceReference1.CommonGatewayMetersReply GetMachineRealMetersByDate(int mID, System.DateTime dt) {
            return base.Channel.GetMachineRealMetersByDate(mID, dt);
        }
    }
}
